Fix external-dns (#59)
When installing external-dns, it doesn't do helm update:
  Error: failed to download "bitnami/external-dns" (hint: running `helm repo update` may help)
See: https://github.com/terraform-providers/terraform-provider-helm/issues/438

Using the .url instead of .name (and therefore changing the chart name too)
fixes it.